### ISSUE TITLE
Add configuration for LazyNvim to readme

### ISSUE THREAD

**Issue by TheSaltyLiquorice** [henry-hsieh/riscv-asm-vim#2]
Hi, thanks for your effort with this plugin!

It would be nice to also add LazyNvim to the readme for plugin management. I am using this for my neovim config.

```lua
return {
  {
    "henry-hsieh/riscv-asm-vim",
    ft = { "*.S", "*.s", "riscv_asm" },
    init = function()
      vim.g.riscv_asm_all_enable = true
    end,
  }
}
```

**Comment by henry-hsieh** [comment]
I haven't used lazy.nvim. According to this [page](https://www.reddit.com/r/neovim/comments/13jcrnh/how_to_make_lazy_load_vimwiki_only_for_files_with/), it seems that `ft = {"riscv_asm"}` is enough to detect the filetype if `ftdetect` exists, which already provided in this plugin. Could you remove `"*.S"` as well as `"*.s"`, and try again?

Thanks!

**Comment by TheSaltyLiquorice** [comment]
> I haven't used lazy.nvim. According to this [page](https://www.reddit.com/r/neovim/comments/13jcrnh/how_to_make_lazy_load_vimwiki_only_for_files_with/), it seems that `ft = {"riscv_asm"}` is enough to detect the filetype if `ftdetect` exists, which already provided in this plugin. Could you remove `"*.S"` as well as `"*.s"`, and try again?
> 
> Thanks!

Just tried and *.S/s seems to be redundant as you said.

**Comment by henry-hsieh** [comment]
I updated the README. Thanks!
