### ISSUE TITLE
[ Question ] Is this overkill for syntax highlighting?

### ISSUE THREAD

**Issue by JxJxxJxJ** [henry-hsieh/riscv-asm-vim#5]
I have to work with ARMV8 and want just to be able to have my code highlighted properly. So far This plugin is the most colorful one, but am I looking in the right direction? 

Any tips would be appreciated. 
![image](https://github.com/henry-hsieh/riscv-asm-vim/assets/103049321/2d87d432-4e07-4835-94e2-15eb6a92abe3)

**Comment by henry-hsieh** [comment]
I'm not quite understanding your question. Do you mean that you are working with RISC-V and ARM assembly at the same time. However, this plugin is messing your highlight of ARM assembly?

**Comment by JxJxxJxJ** [comment]
Apologies for not being clear enough. I'm working with LEGV8 to be exact and was looking for the best syntax highlighting possible. So far the plugin provides the most colorful one but I was wondering whether if I was looking at the best solution for this problem.

**Comment by henry-hsieh** [comment]
If you are looking for syntax highlighting of ARM ISA, this plugin may not suit for you. This plugin cannot recognize any ARM instruction or register. Especially, RISC-V doesn't use `#` before immediate. Therefore, the immediate in your example has been grayed out. You can check plugins like [arm-syntax-vim](https://github.com/ARM9/arm-syntax-vim) or [vim-gas](https://github.com/HealsCodes/vim-gas).

**Comment by JxJxxJxJ** [comment]
Thank you! I'll check them out
